# ベースイメージとしてNode.jsの最新LTSバージョンを使用
FROM node:18

# 作業ディレクトリを設定
WORKDIR /app

# パッケージマネージャーのキャッシュを利用するためにpackage.jsonとpackage-lock.jsonをコピー
COPY package*.json ./

# 依存関係をインストール
RUN npm install

# アプリケーションのソースコードをコピー
COPY . .

# ビルドコマンドを実行
RUN npm run build

# アプリケーションを起動するためのコマンド
CMD ["npm", "run", "dev"]