version: '3'
services:
  backend:
    image: ghcr.io/graalvm/graalvm-community:23
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: sh -c "./build/libs/your-app"
